"""add roles

Revision ID: 0091b28151db
Revises: 9333027fad60
Create Date: 2023-03-17 16:42:45.647064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0091b28151db'
down_revision = '9333027fad60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        role_enum = postgresql.ENUM('admin', 'student', 'trainer', name='role_enum')
        role_enum.create(op.get_bind())

        batch_op.add_column(sa.Column('role', role_enum, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    banner_status = postgresql.ENUM('admin', 'student', 'trainer', name='role_enum')
    banner_status.drop(op.get_bind())

    with op.batch_alter_table('subscription', schema=None) as batch_op:

        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
