"""empty message

Revision ID: 4de6bdae80b8
Revises: 6a8f74bbed3b
Create Date: 2023-04-19 13:00:28.947848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de6bdae80b8'
down_revision = '6a8f74bbed3b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notif_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_header', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('notif_body', sa.Text(), nullable=True))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('notif_user', schema=None) as batch_op:
        batch_op.drop_column('notif_body')
        batch_op.drop_column('notif_header')

    # ### end Alembic commands ###

