"""empty message

Revision ID: 64888c61bc33
Revises: 9d39ab217d92
Create Date: 2023-04-12 14:41:37.752724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64888c61bc33'
down_revision = '9d39ab217d92'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notif_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from', sa.Integer(), nullable=True),
    sa.Column('type', postgresql.ENUM('subscription', 'for_all', 'direct', name='notification_type_enum'), nullable=False),
    sa.Column('subscription', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from'], ['trainer.id'], ),
    sa.ForeignKeyConstraint(['subscription'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    op.drop_table('notification')
    op.drop_table('notif_user')
    # ### end Alembic commands ###

