"""empty message

Revision ID: baf025441003
Revises: d1639523ae34
Create Date: 2023-04-20 16:35:50.559132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf025441003'
down_revision = 'd1639523ae34'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('notif_header', sa.String(length=64), nullable=True),
    sa.Column('notif_body', sa.Text(), nullable=True),
    sa.Column('receive_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notif_user')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    op.create_table('notif_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notif_header', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('notif_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['user.id'], name='notif_user_from_id_fkey'),
    sa.ForeignKeyConstraint(['to_id'], ['user.id'], name='notif_user_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notif_user_pkey')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###

