"""empty message

Revision ID: cca51b000ba1
Revises: d19195f3ae84
Create Date: 2023-04-21 16:08:55.522998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca51b000ba1'
down_revision = 'd19195f3ae84'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_training',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('rank', sa.Integer(), autoincrement=True, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)

    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_training_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('from_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('to_time', sa.Time(), nullable=True))
        batch_op.drop_constraint('training_trainer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'daily_training', ['daily_training_id'], ['id'])
        batch_op.drop_column('trainer_id')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('training_trainer_id_fkey', 'trainer', ['trainer_id'], ['id'])
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')
        batch_op.drop_column('daily_training_id')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)

    op.drop_table('daily_training')
    # ### end Alembic commands ###

