"""empty message

Revision ID: d19195f3ae84
Revises: 81e6da65dd7a
Create Date: 2023-04-20 17:23:33.600384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19195f3ae84'
down_revision = '81e6da65dd7a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.drop_column('notif_header')
        batch_op.drop_column('notif_body')

    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.drop_column('sport')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
        batch_op.drop_column('sub_name')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('name')

    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sport', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_body', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notif_header', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.drop_column('body')
        batch_op.drop_column('header')

    # ### end Alembic commands ###

