name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3

      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest

  send-success-notif:
    runs-on: ubuntu-latest
    needs: build
    if:  ${{ needs.build.result == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: successful_notify
        run: |
          sudo sh tg_notification.sh success

  send-failed-notif:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.result == 'failure' }}
    steps:
      - uses: actions/checkout@v3
      - name: failure_notify
        run: |
          - sudo sh notification_bot.sh failed
        

  tmate_activate:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v3
      - name: create Tmate
        uses: mxschmitt/action-tmate@v3
