name: Python application

on:
  push:
    branches: [ "develop", "CI_CD_branch" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3

      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --system
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest
#    - name: Setup tmate session
#      if: success() || failure()
#      uses: mxschmitt/action-tmate@v3

  send-success-notif:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: successful_notify
        if: needs.build.result == success()
        run: |
          sh notification_bot.sh ✅

  send-failed-notif:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Setup tmate session
        if: needs.build.result == failure()
        uses: mxschmitt/action-tmate@v3
#        if: failure()
#        script:
#          - sh notification_bot.sh ❌
#      - name: failure_notify
#        uses: actions/checkout@v3
